services:
  postgres:
    image: postgres:17
    container_name: smart-office-db
    restart: always

    environment:
      POSTGRES_USER: smart_user
      POSTGRES_PASSWORD: smart_password
      POSTGRES_DB: smart_office

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: