"""rename senha to senha_hash

Revision ID: 52788dca4794
Revises: 4b3f9e63ac0d
Create Date: 2026-07-08 11:25:14.606463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52788dca4794'
down_revision: Union[str, Sequence[str], None] = '4b3f9e63ac0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha_hash', sa.String(length=255), nullable=False))
    op.drop_column('users', 'senha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'senha_hash')
    # ### end Alembic commands ###
